services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      TZ: 'America/Sao_Paulo'
      RUST_LOG: debug
      DATABASE_URL: postgres://user:secret@postgres:5432/my_money
    command: cargo watch -x run
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    container_name: app_db
    restart: always
    image: 'postgres:16-alpine'
    ports:
      - '5432:5432'
    environment:
      TZ: 'America/Sao_Paulo'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-secret}'
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_DB: '${POSTGRES_DB:-my_money}'
    volumes:
      - 'app_db:/var/lib/postgresql/data:rw'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app_db:
    driver: local
